<?php
/* Template Name: About */
get_header();
?>
<div>
	<center>	<b>	<h1>BOICEMY</h1></b>

			
<p>BOICEMY IS AN AUTHORIZED STORE WHERE YOU CAN FIND AN AUTHENTIC SKIN CARE PRODUCTS OF BRILLIANT SKIN ESSENTIALS LIKE  BEAUTY</p><p>REGIMEN,HEALH SUPPLEMENT,SPA AND ETC. AND OTHER  PRODUCTS SUCH AS CLOTHES, BEDSHEETS, GOURMET, AND ETC.  ERIKA ESTOBERO, IS A</p><p> YOUNG CEO OF BOICEMY WHO’S REACHING HER DREAMS TO BE ONE OF THE MOST SUCCESFUL ENTREPENUER.</p>


<b><i><p>ERIKA J. ESTOBERO</p></i></b>
<b><p>CEO
</p></b>

</div> </center>

<?php get_footer(); ?> 
